name: pheno-maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.13
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
      - anndata==0.12.7
      - leidenalg
      - manhole
      - scanpy
      - zarr
      - muon
      - mudata
      - tables
      - pyyaml
      - requests