name: pheno-maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - numpy
  - pandas
  - scipy
  - pip
  - dask
  - pip:
      - anndata
      - leidenalg
      - manhole
      - scanpy
      - zarr
      - muon
      - mudata
      - tables
      - pyyaml
      - requests
      - 'rapids-singlecell-cu13[rapids]' --extra-index-url=https://pypi.nvidia.com
      - cupy-cuda13x
      - tensorflow
      - cuml-cu13